name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Jest
        run: npm test

      - name: Run Cucumber (BDD)
        run: npm run test:bdd

      # Start server BEFORE UI & API tests
      - name: Start API server
        run: |
          node src/index.js > server.log 2>&1 &
          echo $! > server.pid
          # wait until health endpoint is ready (max ~30s)
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:5000/health >/dev/null; then
              echo "API is up";
              break;
            fi
            sleep 1
          done

      - name: Run Playwright
        env:
          BASE_URL: http://127.0.0.1:5000
        run: npm run test:ui

      - name: Newman collection
        run: npx newman run postman/TickyTrack.postman_collection.json -e postman/local.postman_environment.json

      - name: Artillery smoke
        run: npx artillery run -q artillery.yml

      - name: Stop API server
        if: always()
        run: |
          if [ -f server.pid ]; then kill "$(cat server.pid)" || true; fi
          echo "---- last 200 lines of server.log ----"
          tail -n 200 server.log || true
