name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASS: root
      DB_NAME: ticky_track
      DB_PORT: 3306
      PORT: 5000
      CI: true

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Jest
        run: npm test --runInBand

      - name: Run Cucumber (BDD)
        run: npm run test:bdd

      - name: Run Playwright
        run: npm run test:ui

      - name: Start API server
        run: |
          nohup node src/index.js > server.log 2>&1 &
          echo $! > server.pid
          echo "Waiting for /health..."
          for i in {1..30}; do
            if curl -sf "http://127.0.0.1:5000/health" >/dev/null; then
              echo "API is up"; break
            fi
            sleep 2
          done

      - name: Newman collection
        run: npm run test:api:newman

      - name: Artillery smoke
        run: npm run perf:artillery

      - name: Print server log on failure
        if: failure()
        run: |
          echo "--------- server.log ---------"
          cat server.log || true
          echo "------------------------------"

      - name: Stop API server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill -9 "$(cat server.pid)" || true
          fi
